### ISSUE TITLE
error 1x1 MacBook pro mid 2012

### ISSUE THREAD

**Issue by lexi1221** [BenSova/Patched-Sur#42]
Password:mount_apfs: volume not to be mounted: ..........
<img width="602" alt="Screenshot 2020-11-15 at 02 51 35" src="https://user-images.githubusercontent.com/74479050/99161786-7e1f0980-26ed-11eb-90b6-10169e624302.png">

**Comment by BenSova** [comment]
Just restart your Mac, then try again.

**Comment by lexi1221** [comment]
I have, is it because my MacBook ssd is an AFPS ?

**Comment by BenSova** [comment]
No, that's what all Macs should be. Just restart and it should be fixed.

**Comment by lexi1221** [comment]
it is not fixed, I don't know what to do and it gets quite hot as well

**Comment by BenSova** [comment]
Wait, I just realized, why did you create two issues?

**Comment by lexi1221** [comment]
yes sorry by accident, have you seen the red box or want me to post it again? I don't what to do, it seems to run only on Nvidia graphics and it quite hot as well on the keyboard area

**Comment by BenSova** [comment]
Yeah I saw it. My suggestion is to turn it off and let it sit for a little while and try again or do the same thing but leave it on.

**Comment by inregistrare** [comment]
Hi BenSova...same error on iMac late 2012

**Comment by jfmoots** [comment]
Same on a Mac Pro (fake) 5,1

**Comment by BenSova** [comment]
I'm going to need you guys to retest that with v0.0.4 when it comes out. The "internal error" is something that is now better explained with v0.5.1, so hopefully, I can debug it better when v0.0.4 comes out with support for v0.5.1.

**Comment by jfmoots** [comment]
Sounds good! Just to be clear, to try again, I would just rebuild the USB installer with the new DMG. Then I can run the same Sur Patcher application from the Applications folder? It seems like it's running off the USB Installer.

**Comment by jfmoots** [comment]
Just an update. Via Terminal I was able to get patchkexts.sh to run using the --wifi=hv12v-old option

**Comment by ollyboustead** [comment]
Hi - here i smy output text from Macbook pro mid2012 -

@jfmoots What was the terminal command you used to instergate -wifi=hv12-old option 
Is that worth a go?
or shall i wait for 0.0.4

Error 1x1
Message: "Password:a BootKernelExtensions.kc
a SystemKernelExtensions.kc
The operation couldn’t be completed. (kmutil.KMError error 25.)"
"No WiFi option specified on command line, so checking for 802.11ac...
No 802.11ac WiFi card detected, so installing mojave-hybrid WiFi patch.
No patch mode specified on command line. Detecting Mac model...
(Use --2010, --2011, or --2012 command line option to override.)
Detected model: MacBookPro9,2
Detected a 2012-2013 Mac. Using --2012 patch mode.
Installing kexts to:
/

Volume appears to have a Big Sur installation (build 20B29). Continuing.
Volume is mounted from device:  /dev/disk2s2s1
Mounted device is a snapshot. Will now mount underlying volume
from device /dev/disk2s2 at temporary mountpoint:
/System/Volumes/Update/mnt1

Checking for KernelCollections backup...
Backup not found. Performing backup now. This may take a few minutes.
Backing up original KernelCollections to:
/System/Volumes/Update/mnt1/System/Library/KernelCollections/KernelCollections-20B29.tar.lz4
Beginning patched IO80211Family.kext installation
Installing mojave-hybrid WiFi patch
Using kmutil to rebuild boot collection...
Using kmutil to rebuild system collection...
kmutil failed. See above output for more information.
patch-kexts.sh cannot continue."

**Comment by jfmoots** [comment]
https://github.com/barrykn/big-sur-micropatcher

Step 15 outlines running the kexts manually. 

/Volumes/Image\ Volume/patch-kexts.sh /Volumes/Macintosh\ HD --wifi=hv12-old is what I ran. 

Keep in mind, my machine is a Mac Pro 4,1 flashed to 5,1 with upgraded AC wifi. So there's some uncommon about my config that is likely messing with my kexts.

**Comment by BenSova** [comment]
@lexi1221 Can you try again with the latest version of the patcher and Big Sur?
